"""post

Revision ID: 58ee19b221c1
Revises: deb5115f4e26
Create Date: 2022-12-15 19:54:37.251557
"""
# from alembic import op
# import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '58ee19b221c1'
down_revision = 'deb5115f4e26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
