"""social

Revision ID: 751cf7e7e63f
Revises: 58ee19b221c1
Create Date: 2022-12-15 19:54:56.943035
"""
# from alembic import op
# import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '751cf7e7e63f'
down_revision = '58ee19b221c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
