"""initial

Revision ID: deb5115f4e26
Revises:
Create Date: 2022-12-15 19:44:33.663010
"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = 'deb5115f4e26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'social',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('from_user', sa.Integer(), nullable=True),
        sa.Column('to_user', sa.Integer(), nullable=True),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['from_user'],
            ['user.id'],
        ),
        sa.ForeignKeyConstraint(
            ['to_user'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social')
    # ### end Alembic commands ###
